const A=document.querySelector('#app'),qs=s=>document.querySelector(s);
let slide=0,room,token,state,uiTimer,questionTimer,shownResult=0;
const slides=[
 ['الهدف','دولتان تتنافسان على 24 أرضًا. أول دولة تصل إلى 13 أرضًا تفوز بالمملكة.'],
 ['اختيار اللاعب','يختار النظام لاعبًا عشوائيًا، ثم تظهر الخريطة. لا يتكرر اللاعب حتى يمر جميع لاعبي دولته.'],
 ['التوسع','اختر أرضًا محايدة مجاورة لدولتكم. الإجابة الصحيحة تضم الأرض، وبعدها تظهر الخريطة خمس ثوانٍ لرؤية التغيير.'],
 ['المزايا السرية','لا تبدأ أي دولة بمساعدات. بعض الأراضي المحايدة تخفي غششني أو إجابتين أو مشاورة أو دبلها، ولا تُكشف إلا عند اختيار الأرض.'],
 ['دبلها','إذا امتلكتم دبلها فستظهر فوق الخريطة. فعّلوها قبل اختيار الأرض لتحصلوا على أرضين محايدتين متجاورتين عند الإجابة الصحيحة.'],
 ['مهاجمة الخصم','يمكن مهاجمة أرض خصم ملاصقة. تبدأ مواجهة أسرع إجابة؛ يعرض الحكم الإجابة ثم يحدد أي دولة أجابت أولًا.'],
 ['نتيجة الهجوم','إذا سبق المهاجم يأخذ الأرض، وإذا سبق المدافع تبقى أرضه، وإذا لم يجب أحد فلا تتغير الخريطة.'],
 ['الفوز وأفضل لاعب','عند وصول دولة إلى 13 أرضًا تظهر شاشة الفوز وأفضل لاعب، بحسب الإجابات الصحيحة ثم متوسط سرعة الإجابة.']
];
function home(){A.innerHTML=`<section class="hero"><div><p class="subtitle">لعبة الاستراتيجية والثقافة</p><h1 class="brand">ممالك المعرفة</h1><button class="primary" id="newGame">ابدأ لعبة جديدة</button></div></section>`;qs('#newGame').onclick=showSlide}
function slideVisual(i){if(i===1)return `<figure class="rule-visual map-preview"><img src="world-map-v2.png" alt="صورة خريطة ممالك المعرفة"><figcaption>الأرقام هي الأراضي التي تتوسع الدولتان بينها</figcaption></figure>`;if(i===3)return `<div class="rule-visual helper-preview"><div>💡<b>غششني</b><small>أول حرف</small></div><div>✌️<b>إجابتين</b><small>محاولتان</small></div><div>💬<b>مشاورة</b><small>نقاش الفريق</small></div><div>×2<b>دبلها</b><small>أرضان</small></div></div>`;if(i===5)return `<div class="rule-visual duel-preview"><span class="duel-team">الدولة الأولى</span><strong>⚔ أسرع إجابة</strong><span class="duel-team">الدولة الثانية</span></div>`;return ''}
function showSlide(){let s=slides[slide];A.innerHTML=`<section class="panel glass slides"><div><span>${slide+1} / ${slides.length}</span><h1>${s[0]}</h1><p>${s[1]}</p>${slideVisual(slide)}<button class="primary" id="next">${slide===slides.length-1?'إعداد المباراة':'التالي'}</button></div></section>`;qs('#next').onclick=()=>++slide<slides.length?showSlide():setup()}
function colorOptions(selected){let colors=[['#187fa0','أزرق'],['#b83c4b','أحمر'],['#258b58','أخضر'],['#d79b25','ذهبي'],['#7145a5','بنفسجي'],['#d4662f','برتقالي']];return colors.map(([v,n])=>`<option value="${v}" ${v===selected?'selected':''}>${n}</option>`).join('')}
function setup(){A.innerHTML=`<section class="panel glass setup"><div class="logo">إعداد المملكة</div><div class="row">${[0,1].map(i=>`<div class="country-setup"><input id="country${i}" value="الدولة ${i+1}"><label class="color-field">لون الدولة <select id="color${i}">${colorOptions(i?'#b83c4b':'#187fa0')}</select></label><div class="player-count"><button data-minus="${i}">−</button><b id="countLabel${i}">4 لاعبين</b><button data-plus="${i}">+</button></div><input id="count${i}" type="hidden" value="4"><div id="players${i}"></div></div>`).join('')}</div><section class="game-settings"><h2>إعدادات المباراة</h2><label><input id="sideMissions" type="checkbox" checked> تفعيل المهام الجانبية</label><label>تظهر كل <select id="sideInterval"><option value="2">جولتين</option><option value="3">3 جولات</option><option value="4">4 جولات</option></select></label><label>صعوبة الأسئلة <select id="difficulty"><option value="random">عشوائية</option><option value="easy">سهلة</option><option value="medium">متوسطة</option><option value="hard">صعبة</option></select></label></section><button class="primary" id="make">ابدأ المباراة</button></section>`;for(let i=0;i<2;i++)players(i);document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>changeCount(+b.dataset.plus,1));document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>changeCount(+b.dataset.minus,-1));qs('#sideMissions').onchange=()=>qs('#sideInterval').disabled=!qs('#sideMissions').checked;qs('#make').onclick=create}
function changeCount(i,d){let e=qs('#count'+i),n=Math.min(12,Math.max(1,+e.value+d));e.value=n;qs('#countLabel'+i).textContent=`${n} ${n===1?'لاعب':'لاعبين'}`;players(i)}
function players(i){let n=+qs('#count'+i).value,old=[...document.querySelectorAll('.p'+i)].map(x=>x.value);qs('#players'+i).innerHTML=Array.from({length:n},(_,j)=>`<input class="p${i}" value="${old[j]||`لاعب ${j+1}`}" placeholder="اسم اللاعب ${j+1}">`).join('')}
async function call(path,method='GET',data){let r=await fetch(path,{method,headers:{'content-type':'application/json','x-host-token':token||''},body:data?JSON.stringify(data):null}),x=await r.json();if(!r.ok)throw Error(x.error);return x}
async function create(){let countries=[0,1].map(i=>({name:qs('#country'+i).value,color:qs('#color'+i).value,players:[...document.querySelectorAll('.p'+i)].map(x=>x.value)}));if(countries[0].color===countries[1].color)return alert('اختر لونًا مختلفًا لكل دولة');let settings={sideMissions:qs('#sideMissions').checked,sideInterval:+qs('#sideInterval').value,difficulty:qs('#difficulty').value},excluded=JSON.parse(localStorage.getItem('mamalik-used-v3')||'[]');let x=await call('/api/create','POST',{countries,settings,excluded});room=x.room;token=x.token;state=x.state;render()}
function saveUsed(){let a=new Set(JSON.parse(localStorage.getItem('mamalik-used-v3')||'[]'));state.used?.forEach(x=>a.add(x));localStorage.setItem('mamalik-used-v3',JSON.stringify([...a]))}
async function act(action,data={}){clearInterval(questionTimer);try{state=await call(`/api/${room}/action`,'POST',{action,...data});saveUsed();if(state.lastResult?.id&&state.lastResult.id!==shownResult){shownResult=state.lastResult.id;return result(state.lastResult)}if(state.phase==='countdown')return countdown();render()}catch(e){alert(e.message);render()}}
function header(){return `<header class="topbar"><div class="logo">♜ ممالك المعرفة</div><div class="score">${state.countries.map((x,i)=>`<div class="nation" style="border-color:${x.color}">${x.name} · ${state.lands.filter(l=>l.owner===i).length}</div>`).join('')}</div></header>`}
function board(){return `<div class="board"><div class="map">${state.lands.map((l,i)=>`<button class="land ${state.targets.includes(i)?'sel':''}" style="${l.owner!==null?`background:${state.countries[l.owner].color}`:''}" data-i="${i}"><b>${i+1}</b><small>${l.category}</small></button>`).join('')}</div></div>`}
function render(){clearTimeout(uiTimer);clearInterval(questionTimer);let c=state.countries[state.turn];if(state.phase==='draw')return draw(c);if(state.phase==='choose')return choose(c);if(state.phase==='question'||state.phase==='steal')return normalQuestion(c);if(state.phase==='duel')return duel();if(state.phase==='sideMission')return sideMission();if(state.phase==='sideChoose')return sideChoose();if(state.phase==='mapResult')return mapResult();if(state.phase==='finished')return victory();A.innerHTML=''}
function draw(c){A.innerHTML=`<main class="panel">${header()}<section class="control glass"><div class="turn">دور ${c.name}</div><div class="player-reel" id="reel">${c.players[0]}</div><p id="drawText">جاري اختيار اللاعب...</p><button class="primary draw-next" id="goMap" hidden>التالي</button></section></main>`;let r=qs('#reel'),n=0,spin=setInterval(()=>r.textContent=c.players[n++%c.players.length],100);uiTimer=setTimeout(()=>{clearInterval(spin);r.textContent=c.players[state.player];qs('#drawText').textContent='اللاعب المختار';qs('#goMap').hidden=false;qs('#goMap').onclick=()=>act('reveal')},2400)}
function choose(c){A.innerHTML=`<main class="map-only"><div class="map-toolbar"><span>${state.note}</span>${c.helps.double?`<button id="armDouble" class="draw-double">دبلها (${c.helps.double})</button>`:''}</div>${board()}</main>`;if(qs('#armDouble'))qs('#armDouble').onclick=()=>act('armDouble');document.querySelectorAll('.land').forEach(b=>b.onclick=()=>act('target',{index:+b.dataset.i}))}
function countdown(){let n=5;A.innerHTML=`<section class="result-screen countdown-screen"><div><p>${state.note}</p><h1 class="countdown-five">${n}</h1><h2>سيبدأ السؤال</h2></div></section>`;uiTimer=setInterval(()=>{if(--n<=0){clearInterval(uiTimer);act('start')}else qs('.countdown-five').textContent=n},1000)}
function result(r){A.innerHTML=`<section class="result-screen ${r.correct?'good':'bad'}"><div><div class="result-icon">${r.correct?'✓':'✕'}</div><h1 class="result-title">${r.correct?'إجابة صحيحة':'إجابة خاطئة'}</h1>${!r.correct&&r.final?`<div class="correct-reveal">الإجابة الصحيحة: ${r.answer}</div>`:''}</div></section>`;uiTimer=setTimeout(render,!r.correct&&r.final?3500:2000)}
function normalQuestion(c){let steal=state.phase==='steal';A.innerHTML=`<main class="panel">${header()}<section class="control glass"><h2>${steal?`فرصة ${state.countries[1-state.turn].name}`:c.players[state.player]}</h2><div class="question-timer" id="timer"></div><div class="question">${state.question.text}</div>${state.hint?`<p class="answer-hint">أول حرف: ${state.hint}</p>`:''}<div class="answerbox"><input id="typed" placeholder="اكتب الإجابة">${state.twoAnswers&&!steal?'<input id="typed2" placeholder="الإجابة الثانية">':''}<button class="action" id="send">اعتماد الإجابة</button></div>${steal?'':`<div class="helpers">${c.helps.consult?`<button data-helper="consult">مشاورة (${c.helps.consult})</button>`:''}${c.helps.hint?`<button data-helper="hint">غششني (${c.helps.hint})</button>`:''}${c.helps.twoAnswers?`<button data-helper="twoAnswers">إجابتين (${c.helps.twoAnswers})</button>`:''}</div>`}<p class="note">${state.note}</p></section></main>`;document.querySelectorAll('[data-helper]').forEach(b=>b.onclick=()=>act('helper',{helper:b.dataset.helper}));qs('#send').onclick=()=>act(steal?'steal':'submit',{text:qs('#typed').value,text2:qs('#typed2')?.value||''});timer(steal?'steal':'submit')}
function timer(expireAction){let expired=false,tick=()=>{let left=Math.max(0,Math.ceil((state.endsAt-Date.now())/1000));qs('#timer').textContent=left;if(!left&&!expired){expired=true;act(expireAction,{text:''})}};tick();questionTimer=setInterval(tick,250)}
function duel(){let shown=state.answerShown;A.innerHTML=`<main class="panel duel-page">${header()}<section class="control glass"><h2>⚔ مواجهة أسرع إجابة</h2><div class="question-timer" id="timer"></div><div class="question">${state.question.text}</div>${shown?`<div class="correct-reveal">الإجابة: ${state.question.answer}</div><h3>من أجاب أولًا؟</h3><div class="duel-buttons"><button data-team="0">${state.countries[0].name}</button><button data-team="1">${state.countries[1].name}</button><button id="nobody">لم يجب أحد</button></div>`:'<button class="primary" id="showAnswer">عرض الإجابة</button>'}</section></main>`;if(shown){qs('#timer').textContent='—';document.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>act('duelResult',{team:+b.dataset.team}));qs('#nobody').onclick=()=>act('duelResult',{team:null})}else{qs('#showAnswer').onclick=()=>act('revealAnswer');timer('revealAnswer')}}
function sideMission(){A.innerHTML=`<section class="side-mission"><div class="mission-icon">★</div><h1>مهمة جانبية</h1><p>نفّذوا المسابقة خارج اللعبة، ثم اختر الدولة الفائزة.</p><h2>من فاز بالمهمة؟</h2><div class="duel-buttons"><button data-side-team="0" style="background:${state.countries[0].color}">${state.countries[0].name}</button><button data-side-team="1" style="background:${state.countries[1].color}">${state.countries[1].name}</button></div><small>الدولة الفائزة ستختار أرضين محايدتين من الخريطة</small></section>`;document.querySelectorAll('[data-side-team]').forEach(b=>b.onclick=()=>act('sideWinner',{team:+b.dataset.sideTeam}))}
function sideChoose(){let team=state.sideWinner;A.innerHTML=`<main class="map-only"><div class="map-toolbar"><strong style="color:${state.countries[team].color}">${state.countries[team].name}: اختاروا أرضين محايدتين (${state.sidePicks.length}/2)</strong></div>${board()}</main>`;document.querySelectorAll('.land').forEach(b=>b.onclick=()=>act('target',{index:+b.dataset.i}))}
function mapResult(){A.innerHTML=`<main class="map-only map-result"><div class="map-toolbar"><strong>${state.note}</strong></div>${board()}</main>`;uiTimer=setTimeout(()=>act('continue'),5000)}
function victory(){let w=state.countries[state.winner],b=state.bestPlayer;A.innerHTML=`<section class="victory-screen"><div class="victory-crown">♛</div><p>المملكة الفائزة</p><h1>${w.name}</h1><div class="winner-score">${state.lands.filter(l=>l.owner===state.winner).length} أرضًا</div>${b?`<div class="best-player"><span>نجم المباراة</span><strong>${b.name}</strong><small>${b.correct} إجابات صحيحة${b.avgMs?` · متوسط ${Math.round(b.avgMs/1000)} ث` :''}</small></div>`:''}<button class="primary" onclick="location.reload()">لعبة جديدة</button></section>`}
home();
