import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {extname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {QUESTIONS,choicesFor} from './questions.mjs';
const root=fileURLToPath(new URL('.',import.meta.url)), rooms=new Map();
const json=(r,s,x)=>{r.writeHead(s,{'content-type':'application/json; charset=utf-8'});r.end(JSON.stringify(x))};
const body=async q=>{let s='';for await(const c of q)s+=c;return JSON.parse(s||'{}')};
const shuffle=a=>a.sort(()=>Math.random()-.5), code=()=>Math.random().toString(36).slice(2,7).toUpperCase();
const adj=(a,b)=>{let ar=Math.floor(a/6),br=Math.floor(b/6);return Math.abs(ar-br)+Math.abs(a%6-b%6)===1};
function next(g){g.turn=1-g.turn;let c=g.countries[g.turn];if(!c.bag.length)c.bag=shuffle(c.players.map((_,i)=>i));g.player=c.bag.pop();g.phase='draw';g.question=null;g.targets=[];g.double=false;g.hint=null;g.twoAnswers=false;g.note='جاري سحب اللاعب...';}
const nums={الاولى:1,الاول:1,واحد:1,واحده:1,الثاني:2,الثانيه:2,اثنان:2,اثنين:2,الثالث:3,الثالثه:3,ثلاثه:3,الرابع:4,الرابعه:4,اربعه:4,الخامس:5,الخامسه:5,خمسه:5,السادس:6,السادسه:6,سته:6,السابع:7,السابعه:7,سبعه:7,الثامن:8,الثامنه:8,ثمانيه:8,التاسع:9,التاسعه:9,تسعه:9,العاشر:10,العاشره:10,عشره:10};
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/[،,.!?]/g,' ').split(/\s+/).filter(Boolean).map(w=>nums[w]??w).filter(w=>!['السنه','سنه','العام','عام','عدد','الهجريه','للهجره'].includes(String(w)));
const correct=(given,answer)=>{let a=norm(given),b=norm(answer),aa=a.join(''),bb=b.join('');if(!aa)return false;let an=a.filter(x=>typeof x==='number'),bn=b.filter(x=>typeof x==='number');if(an.length&&bn.length&&an.some(x=>bn.includes(x)))return true;return aa===bb||bb.includes(aa)||aa.includes(bb)};
function publicState(g,host=false){let x=structuredClone(g);if(!host&&x.question)delete x.question.answer;for(let i=0;i<x.lands.length;i++){let l=x.lands[i];if(!l.bonusRevealed)delete l.bonus;if(!x.targets.includes(i))delete l.difficulty}return x}
const seedBonuses=lands=>{let open=shuffle(lands.map((l,i)=>l.owner===null?i:-1).filter(i=>i>=0)).slice(0,10),types=['hint','twoAnswers','consult','double'];open.forEach((i,n)=>lands[i].bonus=types[n%types.length]);return lands};
const difficultyName=d=>d==='easy'?'سهل':d==='medium'?'متوسط':'صعب';
function revealBonus(g,i){let l=g.lands[i];if(!l.bonus||l.bonusRevealed)return '';l.bonusRevealed=true;g.countries[g.turn].helps[l.bonus]++;return l.bonus==='hint'?'ميزة سرية: غششني مجانية!':l.bonus==='twoAnswers'?'ميزة سرية: إجابتان مجانيتان!':l.bonus==='consult'?'ميزة سرية: مشاورة مجانية!':'ميزة سرية: دبلها مجانية!'}
function pick(g,cat,diff){let excluded=new Set([...g.excluded,...g.used]);let pool=QUESTIONS.filter(q=>q.category===cat&&q.difficulty===diff&&!excluded.has(q.id));if(!pool.length)pool=QUESTIONS.filter(q=>q.category===cat&&!excluded.has(q.id));return pool[Math.floor(Math.random()*pool.length)]}
async function api(req,res,url){
 let p=url.pathname.split('/').filter(Boolean);
 if(req.method==='POST'&&url.pathname==='/api/create'){let b=await body(req),id=code(),token=crypto.randomUUID();let cats=[...new Set(QUESTIONS.map(q=>q.category))],levels=['easy','medium','hard'];let lands=seedBonuses(Array.from({length:24},(_,i)=>({owner:[2,3,20,21].includes(i)?0:[6,12,11,17].includes(i)?1:null,category:cats[i%cats.length],difficulty:levels[Math.floor(Math.random()*3)]})));let countries=b.countries.map(c=>({...c,helps:{consult:2,hint:1,twoAnswers:1,double:1},bag:shuffle(c.players.map((_,i)=>i))}));let g={room:id,phase:'choose',turn:1,player:0,countries,lands,targets:[],question:null,used:[],excluded:b.excluded||[],note:'',winner:null};next(g);rooms.set(id,{token,g});return json(res,200,{room:id,token,state:publicState(g,true)});}
 let rm=rooms.get(p[1]);if(!rm)return json(res,404,{error:'الغرفة غير موجودة'});let host=req.headers['x-host-token']===rm.token,g=rm.g;
 if(req.method==='GET')return json(res,200,publicState(g,host));if(!host)return json(res,403,{error:'غير مصرح'});let b=await body(req),a=b.action;
 if(a==='reveal'&&g.phase==='draw'){g.phase='choose';g.note='اختار اللاعب أرضًا ثم حدد مستوى السؤال';return json(res,200,publicState(g,true));}
 if(a==='target'){if(g.phase!=='choose')return json(res,400,{error:'ليس وقت الاختيار'});let i=+b.index,own=g.lands.map((l,j)=>l.owner===g.turn?j:-1).filter(j=>j>=0);if(g.lands[i].owner!==null)return json(res,400,{error:'لا يمكن اختيار أرض مملوكة؛ اختر أرضًا محايدة'});if(g.double&&g.targets.length===1){if(!adj(g.targets[0],i)||i===g.targets[0])return json(res,400,{error:'الأرض الثانية يجب أن تكون بجوار الأرض الأولى'});g.targets.push(i);let bonus=revealBonus(g,i);g.phase='countdown';g.note=`صعوبة السؤال: ${difficultyName(g.lands[g.targets[0]].difficulty)}${bonus?' — '+bonus:''}`;}else{if(!own.some(j=>adj(j,i)))return json(res,400,{error:'اختر أرضًا محايدة ملاصقة لدولتك'});g.targets=[i];let bonus=revealBonus(g,i),info=`صعوبة السؤال: ${difficultyName(g.lands[i].difficulty)}${bonus?' — '+bonus:''}`;if(g.double)g.note=info+' — اختر الأرض الثانية المجاورة';else{g.phase='countdown';g.note=info;}}return json(res,200,publicState(g,true));}
 if(a==='armDouble'&&g.phase==='draw'){let c=g.countries[g.turn];if(!c.helps.double)return json(res,400,{error:'دبلها مستخدمة'});c.helps.double--;g.double=true;g.note='دبلها مفعّلة: اختر أرضين متجاورتين';return json(res,200,publicState(g,true));}
 if(a==='start'&&g.phase==='countdown'){let land=g.lands[g.targets[0]],q=pick(g,land.category,land.difficulty);if(!q)return json(res,409,{error:'انتهت الأسئلة الجديدة في هذا القسم'});g.question=q;g.used.push(q.id);g.phase='question';g.endsAt=Date.now()+30000;g.note=`مستوى السؤال: ${difficultyName(land.difficulty)}`;return json(res,200,publicState(g,true));}
 if(a==='helper'){let h=b.helper,c=g.countries[g.turn];if(!c.helps[h])return json(res,400,{error:'المساعدة منتهية'});if(!g.question)return json(res,400,{error:'ابدأ السؤال أولًا'});c.helps[h]--;if(h==='hint')g.hint=String(g.question.answer).trim().charAt(0);if(h==='twoAnswers')g.twoAnswers=true;if(h==='consult')g.note='سُمح بالمشاورة لهذا السؤال';return json(res,200,publicState(g,true));}
 if(a==='ask'){if(!g.targets.length)return json(res,400,{error:'اختر أرضًا'});let land=g.lands[g.targets[0]],q=pick(g,land.category,b.difficulty||'medium');if(!q)return json(res,409,{error:'انتهت الأسئلة الجديدة في هذا القسم'});g.question=q;g.used.push(q.id);g.phase='question';g.endsAt=Date.now()+30000;g.note='يجيب اللاعب المختار دون نقاش';return json(res,200,publicState(g,true));}
 if(a==='submit'&&g.question){let ok=correct(b.text,g.question.answer)||(g.twoAnswers&&correct(b.text2,g.question.answer));g.lastResult={id:Date.now(),correct:ok,final:ok,given:b.text,answer:g.question.answer};if(ok){for(const i of g.targets)g.lands[i].owner=g.turn;let n=g.lands.filter(l=>l.owner===g.turn).length;if(n>=13){g.phase='finished';g.winner=g.turn}else next(g)}else{g.phase='steal';g.twoAnswers=false;g.hint=null;g.note='انتقل السؤال للدولة الأخرى، والمشاورة مسموحة';g.endsAt=Date.now()+30000;}return json(res,200,publicState(g,true));}
 if(a==='steal'&&g.phase==='steal'){let ok=correct(b.text,g.question.answer);g.lastResult={id:Date.now(),correct:ok,final:true,given:b.text,answer:g.question.answer};if(ok)g.lands[g.targets[0]].owner=1-g.turn;next(g);return json(res,200,publicState(g,true));}
 return json(res,400,{error:'طلب غير صحيح'});
}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml'};
http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://x');if(u.pathname.startsWith('/api/'))return await api(req,res,u);let f=u.pathname==='/'?'index.html':u.pathname.slice(1);let d=await readFile(join(root,f));res.writeHead(200,{'content-type':mime[extname(f)]||'application/octet-stream'});res.end(d)}catch(e){json(res,500,{error:e.message})}}).listen(process.env.PORT||3000);
